"""exercises library and admin role

Revision ID: 0fe06a493da4
Revises: 5f7ec19ef326
Create Date: 2026-08-25 18:21:40.988556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fe06a493da4'
down_revision: Union[str, None] = '5f7ec19ef326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate не отслеживает добавление новых значений в уже
    # существующий Postgres ENUM — добавляем 'admin' в user_role вручную.
    # PostgreSQL 12+ позволяет использовать новое значение в той же транзакции.
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'admin'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('skating', 'stickhandling', 'shooting', 'strength', 'goalie', 'game', name='exercise_category'), nullable=False),
    sa.Column('age_group', sa.Enum('age_6_9', 'age_10_12', 'age_13_plus', name='exercise_age_group'), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='exercise_level'), nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repetitions', sa.String(length=255), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_age_group'), 'exercises', ['age_group'], unique=False)
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_level'), 'exercises', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ПРИМЕЧАНИЕ: удалить значение 'admin' из user_role через downgrade
    # напрямую нельзя — PostgreSQL не поддерживает ALTER TYPE ... DROP VALUE.
    # При необходимости отката потребуется пересоздать enum-тип вручную.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_level'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_age_group'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
