"""ice rental module

Revision ID: 5f7ec19ef326
Revises: b06edd4f07a0
Create Date: 2026-08-25 04:02:40.192926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f7ec19ef326'
down_revision: Union[str, None] = 'b06edd4f07a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ice_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('arena_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('ice_type', sa.Enum('full', 'half', 'third', name='ice_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('available', 'pending', 'booked', 'cancelled', name='slot_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arena_id'], ['arenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ice_slots_arena_id'), 'ice_slots', ['arena_id'], unique=False)
    op.create_index(op.f('ix_ice_slots_date'), 'ice_slots', ['date'], unique=False)
    op.create_table('slot_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('coach_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled_by_coach', name='slot_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['ice_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_requests_coach_id'), 'slot_requests', ['coach_id'], unique=False)
    op.create_index(op.f('ix_slot_requests_slot_id'), 'slot_requests', ['slot_id'], unique=False)
    op.add_column('arenas', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('arenas', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('arenas', sa.Column('ice_size', sa.String(length=100), nullable=True))
    op.add_column('arenas', sa.Column('locker_rooms', sa.Integer(), nullable=True))
    op.add_column('arenas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'arenas', 'users', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arenas', type_='foreignkey')
    op.drop_column('arenas', 'created_at')
    op.drop_column('arenas', 'locker_rooms')
    op.drop_column('arenas', 'ice_size')
    op.drop_column('arenas', 'city')
    op.drop_column('arenas', 'address')
    op.drop_index(op.f('ix_slot_requests_slot_id'), table_name='slot_requests')
    op.drop_index(op.f('ix_slot_requests_coach_id'), table_name='slot_requests')
    op.drop_table('slot_requests')
    op.drop_index(op.f('ix_ice_slots_date'), table_name='ice_slots')
    op.drop_index(op.f('ix_ice_slots_arena_id'), table_name='ice_slots')
    op.drop_table('ice_slots')
    # ### end Alembic commands ###
