"""session duration

Revision ID: 61e9ad33ff71
Revises: f4dd61b2fddf
Create Date: 2026-08-30 04:24:09.350588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61e9ad33ff71'
down_revision: Union[str, None] = 'f4dd61b2fddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'duration_minutes')
    # ### end Alembic commands ###
