"""redesign exercises for card-based catalog

Revision ID: 9a0c08af9c9f
Revises: d2ca4b5cbeb7
Create Date: 2026-09-11 03:54:40.786797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9a0c08af9c9f'
down_revision: Union[str, None] = 'd2ca4b5cbeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ВАЖНО: Alembic autogenerate не создаёт Postgres ENUM-тип автоматически
    # внутри add_column (только внутри create_table) — создаём явно сами,
    # иначе миграция падает с "type ... does not exist".
    exercise_location = postgresql.ENUM('on_ice', 'gym', 'off_ice', name='exercise_location')
    exercise_location.create(op.get_bind(), checkfirst=True)

    exercise_content_status = postgresql.ENUM('complete', 'draft', name='exercise_content_status')
    exercise_content_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('exercises', sa.Column('location', sa.Enum('on_ice', 'gym', 'off_ice', name='exercise_location'), nullable=False, server_default='on_ice'))
    op.add_column('exercises', sa.Column('players_text', sa.String(length=50), nullable=True))
    op.add_column('exercises', sa.Column('duration_text', sa.String(length=50), nullable=True))
    op.add_column('exercises', sa.Column('equipment_text', sa.String(length=255), nullable=True))
    op.add_column('exercises', sa.Column('needs_puck', sa.Boolean(), nullable=True))
    op.add_column('exercises', sa.Column('steps', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('exercises', sa.Column('coach_tips', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('exercises', sa.Column('simplify_tips', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('exercises', sa.Column('complicate_tips', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('exercises', sa.Column('hockey_connection', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('qualities', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.add_column('exercises', sa.Column('content_status', sa.Enum('complete', 'draft', name='exercise_content_status'), nullable=False, server_default='draft'))
    op.add_column('exercises', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.alter_column('exercises', 'video_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_index('ix_exercises_level', table_name='exercises')
    op.create_index(op.f('ix_exercises_code'), 'exercises', ['code'], unique=True)
    op.create_index(op.f('ix_exercises_location'), 'exercises', ['location'], unique=False)
    op.drop_column('exercises', 'level')
    op.drop_column('exercises', 'repetitions')
    op.drop_column('exercises', 'key_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('key_points', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('repetitions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='exercise_level'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_exercises_location'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_code'), table_name='exercises')
    op.create_index('ix_exercises_level', 'exercises', ['level'], unique=False)
    op.alter_column('exercises', 'video_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('exercises', 'image_url')
    op.drop_column('exercises', 'content_status')
    op.drop_column('exercises', 'qualities')
    op.drop_column('exercises', 'hockey_connection')
    op.drop_column('exercises', 'complicate_tips')
    op.drop_column('exercises', 'simplify_tips')
    op.drop_column('exercises', 'coach_tips')
    op.drop_column('exercises', 'steps')
    op.drop_column('exercises', 'needs_puck')
    op.drop_column('exercises', 'equipment_text')
    op.drop_column('exercises', 'duration_text')
    op.drop_column('exercises', 'players_text')
    op.drop_column('exercises', 'location')
    op.drop_column('exercises', 'code')

    postgresql.ENUM(name='exercise_content_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='exercise_location').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
