"""ratings table

Revision ID: b06edd4f07a0
Revises: f6f67137f6bc
Create Date: 2026-08-25 03:55:26.907497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b06edd4f07a0'
down_revision: Union[str, None] = 'f6f67137f6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('skill', sa.Enum('skating', 'stickhandling', 'shooting', 'tactics', 'discipline', name='skill_category'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'player_id', 'skill', name='uq_rating_session_player_skill')
    )
    op.create_index(op.f('ix_ratings_player_id'), 'ratings', ['player_id'], unique=False)
    op.create_index(op.f('ix_ratings_session_id'), 'ratings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_session_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_player_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
