"""arena contact phone

Revision ID: d2ca4b5cbeb7
Revises: 3a92e6e8bb76
Create Date: 2026-09-01 04:29:21.664077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2ca4b5cbeb7'
down_revision: Union[str, None] = '3a92e6e8bb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arenas', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arenas', 'contact_phone')
    # ### end Alembic commands ###
