"""session price and coach search visibility

Revision ID: f4dd61b2fddf
Revises: 0fe06a493da4
Create Date: 2026-08-28 04:41:34.148974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4dd61b2fddf'
down_revision: Union[str, None] = '0fe06a493da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('visible_in_search', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('training_sessions', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'price')
    op.drop_column('coaches', 'visible_in_search')
    # ### end Alembic commands ###
